version: '3.8'

services:
  archaion-analyzer:
    build: .
    container_name: archaion-analyzer
    ports:
      - "9999:9999"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
